### ISSUE TITLE
gettransaction failing for transactions made by other wallets

### ISSUE THREAD

**Issue by craigmacgregor** [navcoindev/navcoin-core#16]
gettransaction is working for txid's generated by the same wallet.

looking up transactions made by other wallets results in:

```
error code: -5
error message:
Invalid or non-wallet transaction id
```

Also related;

getrawtransaction of the same remote transaction id returns a hex value, but then decoderawtransaction is unable to decode resulting in:

```
error code: -22
error message:
TX decode failed
```

**Comment by aguycalled** [comment]
Not an issue but Bitcoin's normal behaviour.

It is necessary to enable txindex=1 in navcoin.conf to be able to use those commands in the indicated manner. Navcoin would require to rebuild database on first run.

Closing.
