### ISSUE TITLE
Error when running navcoin-cli and navcoin-qt 

### ISSUE THREAD

**Issue by alexpimania** [navcoindev/navcoin-core#47]
When I attempt to run any of the files in the /bin folder, to install nav, it results in this error being displayed.
./navcoin-qt: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

I have tried about 10 methods to fix this problem that I have found on the interweb and none of them have worked. This seems quite important as it is completely preventing me from running the nav client on my computer. Thanks 
-Alex

**Comment by aguycalled** [comment]
Looks like an issue on your operating system/packages. Check that you are using the correct build for your architecture (i686 for 32 bits, x86_64 for 64 bits).

**Comment by alexpimania** [comment]
Yep that fixed it. I needed to use the x86_64 version. Thanks

**Comment by 2SI3NX** [comment]
@aguycalled im using navcoin-4.0.6-x86_64-linux-gnu.tar.gz on Ubuntu 16.04 x64bit, and this is still giving me an error . However i dont know if it makes a difference if its a VM?
please help

**Comment by 2SI3NX** [comment]
umm.. am i the only one not getting a hash match for sha256sum navcoin-4.0.6-x86_64-linux-gnu.tar.gz  after downloading from your github releases page?
