### ISSUE TITLE
Stake Status Icon hard to see.

### ISSUE THREAD

**Issue by mogrith** [navcoindev/navcoin-core#56]
I like the power blue/grey button but it is not oblivious to some .
Increase size of icon an maybe put a Yes or No after it?

**Comment by bocyaj** [comment]
my added suggestion, have the icon green when staking, yellow when staking is setting up and red when not staking.  or just add some text "staking is active" in the area below the 1d/7d/30d stake report just like the messages shown when staking isn't active.

**Comment by mogrith** [comment]
Red/Green is hard for color blind to see difference.

**Comment by aguycalled** [comment]
I'm thinking on this:
- Removing the power icon
- Adding a menu option to toggle staking
- Adding a status text when wallet is staking as @bocyaj suggested

Thoughts? Suggestions?

**Comment by bocyaj** [comment]
Great idea. Turning staking on/off isnt going to be a regular thing so
don't see a need for the toggle on the home screen.
