### ISSUE TITLE
Consider reducing block size

### ISSUE THREAD

**Issue by aguycalled** [navcoindev/navcoin-core#7]
Right now, NavCoin Block Size is up to 20MB.

When SegWit gets enabled, it will require reserving 3 times the block size for the witness data (making a total block weight of 80MB).

Reference: https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki

In the current NavCoin Blockchain there is no Block larger than 2MB.

Reducing the block size from 20MB should be considered.

**Comment by mogrith** [comment]
Halving would skill leave a very large amount of room to grow. Also with the idea of dapps there will be a lot of of chain transactions so normal chain will not be a congested even if use picks up a lot.

**Comment by mogrith** [comment]
While devs should have final say. Maybe a poll on slack or forums for new size?

**Comment by aguycalled** [comment]
Even halving to 10MB would let blocks to have a maximum 40MB size. That would make our network vulnerable to dos attacks. Personally I'd reduce block size to a value between 2MB and 4MB (8MB and 16MB including witness in the weight). I'd prefer to choose the lower value in the scale, with such a small block time (30secs) 2MB+witness are fairly enough to handle a big amount of transactions.But I'm also open to maintain a bigger block size due to historical reasons and possible community preferences.

A deeper discussion about this topic is needed before taking a decision.

**Comment by bocyaj** [comment]
My vote is for 2mb as well.  That's 40mb worth of blocks every 10 mins. I think Bitcoin fits about 2000 tx's in a 1mb block, so assuming NAV is the same, that still gives NAV about 130 tx/sec without segwit.

**Comment by mogrith** [comment]
a lot of discussion on  the slack #general channel. With all the info I agree 2MB would work best and it will NOT need a hard fork.

**Comment by aguycalled** [comment]
I must add that I've been running the new 4.0 node with a limited 2MB block size for weeks without any issue.

**Comment by aguycalled** [comment]
Block size reduced to 2MB
